language: python
arch:
  - amd64
  - ppc64le

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install -q numpy psutil
  - pip install -r requirements-dev.txt
install:
  - make build

script:
  - make test
